repos:
  ## terraform
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.83.5
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md        # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true     # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false
          - --args=--hide providers
      # - id: terraform_tfsec
      - id: terraform_validate
        args:
          - --init-args=-lockfile=readonly
          - --args=-json
          - --args=-no-color
          - --hook-config=--retry-once-with-cleanup=true 
      # - id: terraform_providers_lock
      #   args:
      #     - --args=-platform=windows_amd64
      #     - --args=-platform=darwin_amd64
      #     - --args=-platform=darwin_arm64
      #     - --args=-platform=linux_amd64
