# # only manual
# trigger: none
# pr: none

# parameters:
#   - name: 'DEV'
#     displayName: 'Run on DEV environment'
#     type: boolean
#     default: True
#     values:
#       - False
#       - True
#   - name: 'UAT'
#     displayName: 'Run on UAT environment'
#     type: boolean
#     default: True
#     values:
#       - False
#       - True
#   - name: 'PROD'
#     displayName: 'Run on PROD environment'
#     type: boolean
#     default: True
#     values:
#       - False
#       - True

# variables:
#   TIME_OUT: 10
#   # working dir
#   WORKING_DIR: 'src/aks-platform'
#   DOMAIN_NAME: aks-platform
#   poolNameDev: '$(TF_POOL_NAME_DEV)'
#   poolNameUat: '$(TF_POOL_NAME_UAT)'
#   poolNameProd: '$(TF_POOL_NAME_PROD)'
#   #PLAN
#   azureServiceConnectionPlanNameDev: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_DEV)'
#   azureServiceConnectionPlanNameUat: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_UAT)'
#   azureServiceConnectionPlanNameProd: '$(TF_AZURE_SERVICE_CONNECTION_PLAN_NAME_PROD)'
#   #APPLY
#   azureServiceConnectionApplyNameDev: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_DEV)'
#   azureServiceConnectionApplyNameUat: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_UAT)'
#   azureServiceConnectionApplyNameProd: '$(TF_AZURE_SERVICE_CONNECTION_APPLY_NAME_PROD)'
#   githubEndpointName: '$(TF_GITHUB_SERVICE_ENDPOINT_NAME)'

# pool:
#   vmImage: 'ubuntu-latest'

# resources:
#   repositories:
#     - repository: terraform
#       type: github
#       name: pagopa/azure-pipeline-templates
#       ref: refs/tags/v5.2.1
#       endpoint: 'io-azure-devops-github-ro'

# stages:
# #DEV
#   - ${{ if eq(parameters['DEV'], true) }}:
#     - template: templates/terraform-plan-apply/template.yaml@terraform
#       parameters:
#         FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}"
#         TF_ENVIRONMENT_FOLDER: "weu-dev"
#         ENVIRONMENT: "DEV"
#         AZURE_DEVOPS_POOL_AGENT_NAME: "${{variables.poolNameDev}}"
#         WORKINGDIR: ${{ variables.WORKING_DIR }}
#         AZURE_SERVICE_CONNECTION_PLAN_NAME: "${{variables.azureServiceConnectionPlanNameDev}}"
#         AZURE_SERVICE_CONNECTION_APPLY_NAME: "${{variables.azureServiceConnectionApplyNameDev}}"
# #UAT
#   - ${{ if eq(parameters['UAT'], true) }}:
#     - template: templates/terraform-plan-apply/template.yaml@terraform
#       parameters:
#         FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}"
#         TF_ENVIRONMENT_FOLDER: "weu-uat"
#         ENVIRONMENT: "UAT"
#         AZURE_DEVOPS_POOL_AGENT_NAME: "${{variables.poolNameUat}}"
#         WORKINGDIR: ${{ variables.WORKING_DIR }}
#         AZURE_SERVICE_CONNECTION_PLAN_NAME: "${{variables.azureServiceConnectionPlanNameUat}}"
#         AZURE_SERVICE_CONNECTION_APPLY_NAME: "${{variables.azureServiceConnectionApplyNameUat}}"
# #PROD
#   - ${{ if eq(parameters['PROD'], true) }}:
#     - template: templates/terraform-plan-apply/template.yaml@terraform
#       parameters:
#         FULL_DOMAIN_NAME: "${{variables.DOMAIN_NAME}}"
#         TF_ENVIRONMENT_FOLDER: "weu-prod"
#         ENVIRONMENT: "PROD"
#         AZURE_DEVOPS_POOL_AGENT_NAME: "${{variables.poolNameProd}}"
#         WORKINGDIR: ${{ variables.WORKING_DIR }}
#         AZURE_SERVICE_CONNECTION_PLAN_NAME: "${{variables.azureServiceConnectionPlanNameProd}}"
#         AZURE_SERVICE_CONNECTION_APPLY_NAME: "${{variables.azureServiceConnectionApplyNameProd}}"
